#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""One-shot scaffold generator for tau2_airline scenarios.

Reads ``nemo_voice_agent/evaluation/data/tau2_airline/{tasks,tasks_voice,split_tasks}.json``,
filters to the base-split voice-eligible ids, and emits one
``@register_eval_scenario`` class per task across ``group_Nx.py`` modules in
``nemo_voice_agent/evaluation/scenarios/data/tau2_airline/``. 10 tasks per group.

It is
re-run only when the upstream ``tasks.json`` schema changes (the generated
output is versioned; the generator itself is not). See plan §7 item 10.

Usage::

    cd /path/to/NeMo-Voice-Agent
    python scripts/prepare_tau2_data/generate_airline_scaffolds.py

This overwrites any existing ``group_Nx.py`` files in the target directory and
rewrites ``__init__.py`` to side-import them.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import List


REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "nemo_voice_agent" / "evaluation" / "data" / "tau2_airline"
TARGET_PKG = REPO_ROOT / "nemo_voice_agent" / "evaluation" / "scenarios" / "data" / "tau2_airline"
GROUP_SIZE = 10  # 50 base tasks → 5 groups of 10


def load_base_split_ids() -> List[str]:
    """Return base-split ids intersected with the voice-eligible set, sorted numerically."""
    tasks_voice = json.loads((DATA_DIR / "tasks_voice.json").read_text())
    voice_ids = set(tasks_voice.get("configs", {}).keys())

    split_path = DATA_DIR / "split_tasks.json"
    if split_path.exists():
        splits = json.loads(split_path.read_text())
        base_ids = set(splits.get("base", []))
        ids = voice_ids & base_ids
    else:
        ids = voice_ids

    # Sort numerically since airline ids are integers-as-strings.
    return sorted(ids, key=lambda x: int(x) if str(x).isdigit() else x)


def class_name_for(task_id: str) -> str:
    """Map a tau2_airline task id to a Python class name.

    Airline ids are plain integers ("0", "1", ..., "49"), so this is simple.
    Telecom etc. would need more sanitization.
    """
    safe = "".join(ch if ch.isalnum() else "_" for ch in str(task_id))
    return f"Tau2Airline{safe}"


def scenario_name_for(task_id: str) -> str:
    """Map a tau2_airline task id to the @register_eval_scenario `name` attribute."""
    return f"tau2_airline__{task_id}"


GROUP_HEADER = """# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# AUTO-GENERATED by scripts/prepare_tau2_data/generate_airline_scaffolds.py.
# Do not hand-edit — re-run the generator after upstream schema changes.
#
# Adapted from https://github.com/sierra-research/tau2-bench/tree/voice-user-sim-v1.0
# (MIT-licensed) — task ids correspond 1:1 with tau2's ``tasks.json``.

from nemo_voice_agent.evaluation.scenarios import register_eval_scenario
from nemo_voice_agent.evaluation.scenarios.data.tau2_airline.base import (
    Tau2AirlineBaseScenario,
)


"""


def emit_group(group_idx: int, ids: List[str]) -> str:
    """Render a single group_Nx.py source string."""
    parts = [GROUP_HEADER]
    for tid in ids:
        cls = class_name_for(tid)
        name = scenario_name_for(tid)
        parts.append(
            f"@register_eval_scenario\n"
            f"class {cls}(Tau2AirlineBaseScenario):\n"
            f'    name = "{name}"\n'
            f'    tau2_id = "{tid}"\n\n\n'
        )
    return "".join(parts).rstrip() + "\n"


INIT_TEMPLATE = '''# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""tau2_airline scenarios package.

``base.py`` holds ``Tau2AirlineBaseScenario``. ``group_Nx.py`` modules hold
auto-scaffolded scenarios (see scripts/prepare_tau2_data/generate_airline_scaffolds.py).
Importing this package side-imports every group so registry decoration fires
for all {n_total} base-split tau2_airline scenarios.
"""

from nemo_voice_agent.evaluation.scenarios.data.tau2_airline.base import (  # noqa: F401
    Tau2AirlineBaseScenario,
)

# Side-import groups so @register_eval_scenario fires.
{import_lines}
'''


def main() -> int:
    ids = load_base_split_ids()
    n_total = len(ids)
    print(f"Found {n_total} base-split voice-eligible tau2_airline ids.")

    # Chunk into groups of GROUP_SIZE
    groups: List[List[str]] = []
    for i in range(0, n_total, GROUP_SIZE):
        groups.append(ids[i : i + GROUP_SIZE])

    # Compute group naming. For 50 tasks we get 5 groups indexed 0..4.
    # group_0x.py holds ids 0-9, group_1x.py holds 10-19, etc. (assumes integer ids)
    # For other domains with non-integer ids we'd fall back to numeric chunk index.
    group_files = []
    for chunk_idx, group_ids in enumerate(groups):
        try:
            # If all ids are integers, name by first-id-decade.
            decade = int(group_ids[0]) // 10
            group_filename = f"group_{decade}x.py"
        except (ValueError, TypeError):
            group_filename = f"group_{chunk_idx}.py"
        group_files.append(group_filename)

        path = TARGET_PKG / group_filename
        path.write_text(emit_group(chunk_idx, group_ids))
        print(f"  wrote {group_filename}: {len(group_ids)} scenarios (ids {group_ids[0]}..{group_ids[-1]})")

    # Rewrite __init__.py with side-imports
    import_lines = "\n".join(
        f"from nemo_voice_agent.evaluation.scenarios.data.tau2_airline import {f[:-3]}  # noqa: F401"
        for f in sorted(group_files)
    )
    (TARGET_PKG / "__init__.py").write_text(INIT_TEMPLATE.format(n_total=n_total, import_lines=import_lines))
    print(f"  wrote __init__.py with {len(group_files)} group side-imports")

    return 0


if __name__ == "__main__":
    sys.exit(main())
